# Generated by Django 5.1.2 on 2025-07-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(default="", max_length=11, verbose_name="<UNK>"),
        ),
    ]
