# Generated by Django 5.1.2 on 2024-11-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mine',
            fields=[
                ('mine_id', models.AutoField(primary_key=True, serialize=False, verbose_name='矿井ID')),
                ('mine_username', models.CharField(max_length=50, verbose_name='矿井所属用户')),
                ('mine_name', models.CharField(max_length=50, verbose_name='矿井名称')),
                ('mine_desc', models.CharField(max_length=200, verbose_name='矿井描述')),
            ],
            options={
                'verbose_name_plural': '矿井表',
                'db_table': 'Mine',
            },
        ),
    ]
