# Generated by Django 5.1.2 on 2024-12-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreeDMineTunnel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tube_wind_speed', models.CharField(max_length=255, verbose_name='风速')),
                ('point_left_x', models.CharField(max_length=255, verbose_name='左上角X坐标')),
                ('point_left_y', models.CharField(max_length=255, verbose_name='左上角Y坐标')),
                ('point_left_z', models.CharField(max_length=255, verbose_name='左上角Z坐标')),
                ('point_right_x', models.CharField(max_length=255, verbose_name='右上角X坐标')),
                ('point_right_y', models.CharField(max_length=255, verbose_name='右上角Y坐标')),
                ('point_right_z', models.CharField(max_length=255, verbose_name='右上角Z坐标')),
            ],
            options={
                'verbose_name_plural': '三维矿井隧道坐标',
                'db_table': 'ThreeDMineTunnel',
            },
        ),
    ]
