# Generated by Django 5.1.2 on 2025-07-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mines", "0002_threedminetunnel"),
    ]

    operations = [
        migrations.AddField(
            model_name="threedminetunnel",
            name="tube_name",
            field=models.CharField(
                default="Unknown Tunnel", max_length=255, verbose_name="隧道名称"
            ),
            preserve_default=False,
        ),
    ]
