# Generated by Django 5.1.2 on 2025-07-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mines", "0003_threedminetunnel_tube_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="threedminetunnel",
            name="tube_H",
            field=models.CharField(default=3, max_length=255, verbose_name="H值"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="threedminetunnel",
            name="tube_R",
            field=models.CharField(default=2, max_length=255, verbose_name="R值"),
            preserve_default=False,
        ),
    ]
