# Generated by Django 5.1.2 on 2025-08-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mines', '0004_threedminetunnel_tube_h_threedminetunnel_tube_r'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.FloatField(verbose_name='x坐标')),
                ('y', models.FloatField(verbose_name='y坐标')),
                ('z', models.FloatField(verbose_name='z坐标')),
            ],
            options={
                'verbose_name_plural': '节点坐标',
                'db_table': 'Node',
            },
        ),
        migrations.CreateModel(
            name='Tunnel',
            fields=[
                ('tunnel_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_id', models.IntegerField(verbose_name='起点ID')),
                ('end_id', models.IntegerField(verbose_name='终点ID')),
                ('r', models.FloatField(verbose_name='阻力系数')),
                ('q', models.FloatField(verbose_name='风量')),
                ('h', models.FloatField(verbose_name='阻力')),
            ],
            options={
                'verbose_name_plural': '巷道信息',
                'db_table': 'Tunnel',
            },
        ),
    ]
