# Generated by Django 5.1.2 on 2025-08-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mines', '0005_node_tunnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tunnel',
            name='h',
            field=models.FloatField(null=True, verbose_name='阻力'),
        ),
        migrations.AlterField(
            model_name='tunnel',
            name='q',
            field=models.FloatField(null=True, verbose_name='风量'),
        ),
    ]
